name: Build, Test, and Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v23

      - name: Lint Go code
        run: nix develop --command my-lint-script

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v23

      - name: Run tests
        run: nix develop --command my-test-script

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v23

      - name: Build
        run: nix build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: a-go-project
          path: result/

